"""add is_admin

Revision ID: 6acfe18014b1
Revises: f7d0c4f5c534
Create Date: 2026-02-21 23:40:17.990969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6acfe18014b1'
down_revision: Union[str, Sequence[str], None] = 'f7d0c4f5c534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        'users',
        sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('0'))
    )
    op.alter_column('users', 'is_admin', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weeks', 'is_open',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
