"""add poster_url

Revision ID: cec03315aff0
Revises: 8f962a5af715
Create Date: 2026-02-18 17:53:41.984812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec03315aff0'
down_revision: Union[str, Sequence[str], None] = '8f962a5af715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('poster_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'poster_url')
    # ### end Alembic commands ###
