"""add film matching fields

Revision ID: d65d8b1e0838
Revises: 456e9bf97477
Create Date: 2026-02-18 19:17:02.465176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'd65d8b1e0838'
down_revision: Union[str, Sequence[str], None] = '456e9bf97477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()

    # what columns already exist in the real SQLite table?
    existing = {
        row[1] for row in conn.execute(text("PRAGMA table_info('films')")).fetchall()
    }

    def add_col_if_missing(col):
        if col.name not in existing:
            op.add_column("films", col)

    add_col_if_missing(sa.Column("submitted_title", sa.String(), nullable=True))
    add_col_if_missing(sa.Column("submitted_year", sa.Integer(), nullable=True))
    add_col_if_missing(sa.Column("tmdb_id", sa.Integer(), nullable=True))
    add_col_if_missing(sa.Column("match_score", sa.Float(), nullable=True))

    # needs_review must be NOT NULL with a server default for SQLite
    if "needs_review" not in existing:
        op.add_column(
            "films",
            sa.Column(
                "needs_review",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("0"),  # false
            ),
        )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'needs_review')
    op.drop_column('films', 'match_score')
    op.drop_column('films', 'tmdb_id')
    op.drop_column('films', 'submitted_year')
    op.drop_column('films', 'submitted_title')
    # ### end Alembic commands ###
